workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Archive
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -archivePath $CM_ARCHIVE_PATH \
          -sdk iphoneos \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
          clean archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
          -archivePath $CM_ARCHIVE_PATH \
          -exportOptionsPlist export_options.plist \
          -exportPath $CM_BUILD_DIR
    artifacts:
      - build/ios/ipa/*.ipa
